name: Run PR validations
'on': pull_request
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci

      - name: Check linters
        run: npm run lint

      - name: Check tests
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
        run: |
          npm run test
          npm run test:coverage

      - name: Build library
        env:
          NODE_ENV: production
        run: npm run build
